### ISSUE TITLE
Runtime panic using scalar()

### ISSUE THREAD

**Issue by Nklya** [jacksontj/promxy#219]
Hello.
First of all, I would like to say thank you for such a great tool!

## Description

I run into a runtime panic using scalar() function.
My setup consists of a couple of prometheuses on EC2 instances and a couple of prometheuses deployed in Kubernetes with prometheus-operator.

When I try to use the same dashboard that supplied with prometheus-operator at Grafana with promxy datasource, i started to get 502 errors on this query: `node:node_disk_saturation:avg_irate / scalar(:kube_pod_info_node_count:)`

Each of these metrics returned fine when requested in promxy web interface, except `scalar(:kube_pod_info_node_count:)`. And of course, this request runs fine on each of prometheuses.

I haven't found any related issue here. Maybe you can suggest some fix?

## Versions

* prometheus - 2.10.0
* promxy - v0.0.49 (running with docker-compose)

## Config

```yml
---
# Based on https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml
promxy:
  server_groups:
    - static_configs:
        - targets:
          - ec2-host1
      scheme: https
      ignore_error: true
    - static_configs:
        - targets:
          - ec2-host2
      scheme: https
      ignore_error: true
    - static_configs:
        - targets:
          - k8s-host1
      scheme: https
      ignore_error: true
    - static_configs:
        - targets:
          - k8s-host2
      scheme: https
      ignore_error: true
```

## Log

```
promxy_1          | 2019/09/25 12:01:28 http: panic serving 192.168.0.11:38346: interface conversion: string is not error: missing method Error
promxy_1          | goroutine 152391 [running]:
promxy_1          | net/http.(*conn).serve.func1(0xc0006368c0)
promxy_1          | 	/usr/local/go/src/net/http/server.go:1767 +0x139
promxy_1          | panic(0x1e64940, 0xc0001e93b0)
promxy_1          | 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
promxy_1          | github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql.(*evaluator).recover(0xc0007b1130, 0xc0007b0f28)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/engine.go:730 +0x371
promxy_1          | panic(0x1cf3aa0, 0xc0006311a0)
promxy_1          | 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
promxy_1          | github.com/jacksontj/promxy/pkg/promclient.(*SeriesIterator).Next(0xc0006465a0, 0xc0000d0600)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/pkg/promclient/iterators.go:106 +0x181
promxy_1          | github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/storage.(*BufferedSeriesIterator).Reset(0xc0001e9380, 0x273e480, 0xc0006465a0)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/storage/buffer.go:57 +0x83
promxy_1          | github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql.(*evaluator).eval(0xc0007b1130, 0x2721140, 0xc000103730, 0xf, 0xc000bbfe50)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/engine.go:1145 +0x19cd
promxy_1          | github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql.(*evaluator).Eval(0xc0007b1130, 0x2721140, 0xc000103730, 0x0, 0x0, 0x0, 0x0)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/engine.go:736 +0x99
promxy_1          | github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql.(*Engine).execEvalStmt(0xc000124180, 0x273e2c0, 0xc000de2540, 0xc000c98540, 0xc00011a6e0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/engine.go:436 +0x43d
promxy_1          | github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql.(*Engine).exec(0xc000124180, 0x273e2c0, 0xc000de2540, 0xc000c98540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/engine.go:390 +0x5d6
promxy_1          | github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql.(*query).Exec(0xc000c98540, 0x273e200, 0xc0009fa480, 0xc000168a00)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/engine.go:179 +0x94
promxy_1          | github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/web/api/v1.(*API).query(0xc0002f2820, 0xc000853a00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/web/api/v1/api.go:301 +0x377
promxy_1          | github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/web/api/v1.(*API).Register.func1.1(0x2721200, 0xc000b703a0, 0xc000853a00)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/web/api/v1/api.go:205 +0x8e
promxy_1          | net/http.HandlerFunc.ServeHTTP(0xc000119180, 0x2721200, 0xc000b703a0, 0xc000853a00)
promxy_1          | 	/usr/local/go/src/net/http/server.go:2007 +0x44
promxy_1          | github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/util/httputil.CompressionHandler.ServeHTTP(0x26ea520, 0xc000119180, 0x272cf00, 0xc0008c17a0, 0xc000853a00)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/util/httputil/compression.go:90 +0x7c
promxy_1          | github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/web.(*Handler).testReady.func1(0x272cf00, 0xc0008c17a0, 0xc000853a00)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/web/web.go:400 +0x55
promxy_1          | github.com/jacksontj/promxy/vendor/github.com/prometheus/common/route.(*Router).handle.func1(0x272cf00, 0xc0008c17a0, 0xc0000d6900, 0x0, 0x0, 0x0)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/common/route/route.go:77 +0x296
promxy_1          | github.com/jacksontj/promxy/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000124cc0, 0x272cf00, 0xc0008c17a0, 0xc0000d6900)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/vendor/github.com/julienschmidt/httprouter/router.go:334 +0x95e
promxy_1          | github.com/jacksontj/promxy/vendor/github.com/prometheus/common/route.(*Router).ServeHTTP(...)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/common/route/route.go:115
promxy_1          | main.main.func5(0x272cf00, 0xc0008c17a0, 0xc0000d6900)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/cmd/promxy/main.go:324 +0x22b
promxy_1          | net/http.HandlerFunc.ServeHTTP(0xc00035e6c0, 0x272cf00, 0xc0008c17a0, 0xc0000d6900)
promxy_1          | 	/usr/local/go/src/net/http/server.go:2007 +0x44
promxy_1          | github.com/jacksontj/promxy/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000124d80, 0x272cf00, 0xc0008c17a0, 0xc0000d6900)
promxy_1          | 	/go/src/github.com/jacksontj/promxy/vendor/github.com/julienschmidt/httprouter/router.go:395 +0x12a
promxy_1          | net/http.serverHandler.ServeHTTP(0xc00023a000, 0x272cf00, 0xc0008c17a0, 0xc0000d6900)
promxy_1          | 	/usr/local/go/src/net/http/server.go:2802 +0xa4
promxy_1          | net/http.(*conn).serve(0xc0006368c0, 0x273e200, 0xc00103a3c0)
promxy_1          | 	/usr/local/go/src/net/http/server.go:1890 +0x875
promxy_1          | created by net/http.(*Server).Serve
promxy_1          | 	/usr/local/go/src/net/http/server.go:2927 +0x38e
```

**Comment by jacksontj** [comment]
@Nklya Thanks for the report! Its always great to get such detailed bug reports :) I was able to reproduce the issue immediately and have created #220 to resolve the issue.

I've also created a [new release](https://github.com/jacksontj/promxy/releases/tag/v0.0.50) with the fix

**Comment by Nklya** [comment]
Thank you @jacksontj for super-fast fix! 🤗

**Comment by Nklya** [comment]
@jacksontj , I tested updated version today and get another error: `Error executing query: unexpected error: runtime error: invalid memory address or nil pointer dereference` and nothing in logs.

The only difference I found is that promxy for request `scalar(:kube_pod_info_node_count:)` returns:
```
Element | Value
-- | --
{} | 6
```

And prometheus:
```
Element | Value
-- | --
scalar | 6

```

Should I create a new issue?

**Comment by jacksontj** [comment]
@Nklya https://github.com/jacksontj/promxy/pull/221 should cover that case -- since the function can return a scalar we have to handle it in the NodeReplacer as well.

**Comment by Nklya** [comment]
Tested, now it works perfectly!
Thanks again, @jacksontj
