### ISSUE TITLE
Segmentation violation after ~12 hours

### ISSUE THREAD

**Issue by thordendal** [jacksontj/promxy#267]
Version used: `v0.0.57-linux-amd64`
Systemd cmd line:
```shell
/opt/prometheus/bin/promxy \
  --config=/etc/promxy/config.yaml \
  --web.external-url=http://192.168.0.123:9090 \
  --access-log-destination=none \
  --http.shutdown-delay=1s \
  --http.shutdown-timeout=5s
```

/etc/promxy/config.yaml:
```yaml
global:
  evaluation_interval: 15s
  external_labels:
    source: promxy

rule_files:
- "rules.*/*"

promxy:
  server_groups:
    - static_configs:
        - targets:
          - localhost:19090 # Prometheus
      anti_affinity: 10s
      remote_read: true
      remote_read_path: api/v1/read
      query_params:
        nocache: 1
      ignore_error: false
      http_client:
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true

      absolute_time_range:
        start: '2009-10-10T23:00:00Z'
        end: '2020-01-01T23:00:00Z'

    - static_configs:
        - targets:
          - production.victoria-metrics.consul.tech:8428 # VictoriaMetrics
      anti_affinity: 10s
      remote_read: true
      http_client:
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true
      query_params:
        nocache: 1
      ignore_error: true
      absolute_time_range:
        start: '2020-01-01T23:01:00Z'
```

Journald log:
```
Feb 20 05:04:01 promxy-node-01 promxy[68451]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 20 05:04:01 promxy-node-01 promxy[68451]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1b46344] 
Feb 20 05:04:01 promxy-node-01 promxy[68451]: goroutine 242026221 [running]:
Feb 20 05:04:01 promxy-node-01 promxy[68451]: github.com/jacksontj/promxy/pkg/proxystorage.(*OffsetFinder).Visit(0x0, 0x0, 0x0, 0xc000a32320, 0x7, 0xa, 0x26dbe60, 0xc0040a9af0, 0x0, 0x0)
Feb 20 05:04:01 promxy-node-01 promxy[68451]:         /home/tjackson/workspace/golang/src/github.com/jacksontj/promxy/pkg/proxystorage/util.go:63 +0x74
Feb 20 05:04:01 promxy-node-01 promxy[68451]: github.com/jacksontj/promxy/pkg/proxystorage.(*MultiVisitor).Visit(0xc001100160, 0x0, 0x0, 0xc000a32320, 0x7, 0xa, 0x26dbe80, 0xc001100160, 0x0, 0x0)
Feb 20 05:04:01 promxy-node-01 promxy[68451]:         /home/tjackson/workspace/golang/src/github.com/jacksontj/promxy/pkg/proxystorage/util.go:22 +0xee
Feb 20 05:04:01 promxy-node-01 systemd[1]: promxy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```
There was no heavy traffic, no RAM or CPU consumption anomalies. Promxy is listening default port and is used as nginx' upstream. If there is any other info to provide, I'll be glad to help you.

**Comment by jacksontj** [comment]
Thanks for the report! From the backtrace and code it seems to be a data race, I have a fix PRd at https://github.com/jacksontj/promxy/pull/268
