### ISSUE TITLE
Getting memory for Promxy, rules  & remote_write configuration

### ISSUE THREAD

**Issue by gr8Adakron** [jacksontj/promxy#408]
I have integrated rules along with alertmanager and Victorops but as soon as I am configuring remote_write I get the following error:

Error recieving:

```
panic: WHAT

goroutine 1 [running]:
github.com/jacksontj/promxy/pkg/proxystorage.(*ProxyStorage).ApplyConfig(0xc0006e4970, 0xc0001f4960, 0xc0001f4960, 0x0)
	/go/src/github.com/jacksontj/promxy/pkg/proxystorage/proxy.go:122 +0x6fa
main.reloadConfig(0xc0008142a8, 0xc0000c0780, 0x5, 0x8, 0x8, 0x30ff3c0)
	/go/src/github.com/jacksontj/promxy/cmd/promxy/main.go:117 +0xb4
main.main()
	/go/src/github.com/jacksontj/promxy/cmd/promxy/main.go:383 +0x189c
```

My YAML manifestation for Promxy:

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    linkerd.io/inject: enabled
  name: monitoring
---
apiVersion: v1
data:
  alertmanager.yml: "global:\n  # ResolveTimeout is the time after which an alert is declared resolved\n  # if it has not been updated.\n  resolve_timeout: 5m\n  # victorops API KEY and URL\n  #API key in integration\n  victorops_api_key: 60a826c654ff477c923ceac559ea73ae \n  #Rest API in integrations\n  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/96104c13-3550-4e38-8d6e-ac2820fee5b6/$routing_key\ntemplates:\n- './alertmanager-templates/*.tmpl'\nroute:\n  group_by: ['alertname', 'cluster', 'service']\n  group_wait: 30s\n  group_interval: 5m\n  repeat_interval: 3h\n  receiver: victorOps-receiver\nreceivers:\n  - name: victorOps-receiver\n    victorops_configs:\n       #prometheus serviceAPI key\n      - api_key: 780924a4-a14e-4df3-ae9c-b2057d59da50\n       #routing key in settings\n        routing_key: baldor-v1\n        state_message: 'Alert: {{ .CommonLabels.alertname }}. Summary:{{ .CommonAnnotations.summary }}. RawData: {{ .CommonLabels }}'\ninhibit_rules:\n  - source_match:\n      severity: 'critical'\n    target_match:\n      severity: 'warning'\n    equal: ['alertname', 'dev', 'instance']\n"
kind: ConfigMap
metadata:
  name: alertmanager-config-th6k86tkc2
  namespace: monitoring
---
apiVersion: v1
data:
  alertmanager-default.tmpl: |
    {{ define "__alertmanager" }}Alertmanager Template{{ end }}
kind: ConfigMap
metadata:
  name: alertmanager-templates-kbk7dk8bmt
  namespace: monitoring
---
apiVersion: v1
data:
  config.yml: |-
    global:
      evaluation_interval: 5s
      external_labels:
        source: staging

    # Rule files specifies a list of globs. Rules and alerts are read from
    # all matching files.
    rule_files:
    - "/app/rules/*rules"

    # Alerting specifies settings related to the Alertmanager.
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager-svc.monitoring.svc.cluster.local:9093"

    # remote_write configuration is used by promxy as its local Appender, meaning all
    # metrics promxy would "write" (not export) would be sent to this. Examples
    # of this include: recording rules, metrics on alerting rules, etc.
    remote_write:
      - url: http://127.0.0.1:8083/receive

    ##
    ### Promxy configuration
    ##
    promxy:
      server_groups:
        # All upstream prometheus service discovery mechanisms are supported with the same
        # markup, all defined in https://github.com/prometheus/prometheus/blob/master/discovery/config/config.go#L33
        - static_configs:
            - targets:
              - victoria-metrics-1.internal:8428
          # labels to be added to metrics retrieved from this server_group
          labels:
            sg: vm_v1_8428
          # anti-affinity for merging values in timeseries between hosts in the server_group
          anti_affinity: 10s
          # Controls whether to use remote_read or the prom API for fetching remote RAW data (e.g. matrix selectors)
          # Note, some prometheus implementations (e.g. [VictoriaMetrics](https://github.com/prometheus/prometheus/issues/4456) don't support remote_read.
          remote_read: false
          # configures the path to send remote read requests to. The default is "api/v1/read"
          # remote_read_path: api/v1/read
          # path_prefix defines a prefix to prepend to all queries to hosts in this servergroup
          # This can be relabeled using __path_prefix__
          # path_prefix: api/v1/read
          # query_params adds the following map of query parameters to downstream requests.
          # The initial use-case for this is to add `nocache=1` to VictoriaMetrics downstreams
          # (see https://github.com/jacksontj/promxy/issues/202)
          query_params:
            nocache: 1
          # configures the protocol scheme used for requests. Defaults to http
          scheme: http
          # options for promxy's HTTP client when talking to hosts in server_groups
          http_client:
            # dial_timeout controls how long promxy will wait for a connection to the downstream
            # the default is 200ms.
            dial_timeout: 1s
            tls_config:
              insecure_skip_verify: true

          # relative_time_range defines a relative-to-now time range that this server group contains.
          # this is completely optional and start/end are both optional as well
          # an example is if this servergroup only has the most recent 3h of data
          # the "start" would be -3h and the end would be left out
          relative_time_range:
            start: -3h
            end: -1h

          # absolute_time_range defines an absolute time range that this server group contains.
          # this is completely optional and start/end are both optional as well
          # and example is if the servergroup has been deprecated and is no longer receiving data
          # you could set the specific times that it has data for.
          # absolute_time_range:
          #   start: '2009-10-10T23:00:00Z'
          #   end: '2009-10-11T23:00:00Z'
kind: ConfigMap
metadata:
  name: promxy-config-c227m8dtf8
  namespace: monitoring
---
apiVersion: v1
data:
  promxy-example.rules: |-
    # example from https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
    groups:
    - name: example-groups
      rules:
      - alert: HostUnusualDiskWriteRate
        expr: sum by (instance) (rate(node_disk_written_bytes_total[2m])) / 1024 / 1024 > 50
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host unusual disk write rate
kind: ConfigMap
metadata:
  name: promxy-rules-64mfdc82h4
  namespace: monitoring
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
    prometheus.io/path: /metrics
    prometheus.io/scrape: "true"
  labels:
    app: alertmanager
  name: alertmanager-svc
  namespace: monitoring
spec:
  ports:
  - name: alertmanager
    port: 9093
    protocol: TCP
  selector:
    app: alertmanager
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: promxy-int-svc
  namespace: monitoring
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: promxy
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
      name: alertmanager
    spec:
      containers:
      - image: prom/alertmanager
        name: alertmanager
        ports:
        - containerPort: 9093
          name: alertmanager
        volumeMounts:
        - mountPath: /etc/alertmanager
          name: alertmanager-config
        - mountPath: /etc/alertmanager-templates
          name: alertmanager-templates
          readOnly: true
        - mountPath: /alertmanager
          name: alertmanager
      volumes:
      - configMap:
          name: alertmanager-config-th6k86tkc2
        name: alertmanager-config
      - configMap:
          name: alertmanager-templates-kbk7dk8bmt
        name: alertmanager-templates
      - emptyDir: {}
        name: alertmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: promxy
  name: promxy
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promxy
  template:
    metadata:
      labels:
        app: promxy
    spec:
      containers:
      - args:
        - --config=/etc/promxy/config.yml
        - --web.enable-lifecycle
        - --log-level=trace
        command:
        - /bin/promxy
        env:
        - name: ROLE
          value: "1"
        envFrom:
        - configMapRef:
            name: promxy-config-c227m8dtf8
        image: quay.io/jacksontj/promxy:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /-/healthy
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        name: promxy
        ports:
        - containerPort: 8082
          name: web
        readinessProbe:
          failureThreshold: 120
          httpGet:
            path: /-/ready
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        volumeMounts:
        - mountPath: /etc/promxy/
          name: promxy-config
          readOnly: true
        - mountPath: /app/rules/
          name: promxy-rules
          readOnly: true
      - args:
        - --volume-dir=/etc/promxy
        - --webhook-url=http://localhost:8082/-/reload
        image: jimmidyson/configmap-reload:v0.1
        name: promxy-server-configmap-reload
        volumeMounts:
        - mountPath: /etc/promxy/
          name: promxy-config
          readOnly: true
        - mountPath: /app/rules/
          name: promxy-rules
          readOnly: true
      volumes:
      - configMap:
          name: promxy-config-c227m8dtf8
        name: promxy-config
      - configMap:
          name: promxy-rules-64mfdc82h4
        name: promxy-rules

```

Any help will be appreciated!

**Comment by gr8Adakron** [comment]
@jacksontj

**Comment by jacksontj** [comment]
The panic you reported is not in master (it was fixed in https://github.com/jacksontj/promxy/commit/d08e35c24025d819afff84808f7f73c1afdde847). Are you able to reproduce this on master or >=0.0.67 ?

**Comment by gr8Adakron** [comment]
I am using this image `quay.io/jacksontj/promxy:latest` which must be master as the latest one was pushed a month ago. 

Anyway, I tried with pull of v0.0.67 and it worked fine.
`image: quay.io/jacksontj/promxy:v0.0.67`

Thanks for responsing.
